hostname = api.shortcutstudio.app

[rewrite_local]
^https:\/\/api\.shortcutstudio\.app\/generate(?:[/?#]|$) url script-request-body https://raw.githubusercontent.com/Yu9191/shortcutstudio-rewrite/refs/heads/baby/dist/request.js
^https:\/\/api\.shortcutstudio\.app\/users\/me\/limits(?:[/?#]|$) url script-request-header https://raw.githubusercontent.com/Yu9191/shortcutstudio-rewrite/refs/heads/baby/dist/request.js
^https:\/\/api\.shortcutstudio\.app\/sign(?:[/?#]|$) url script-request-header https://raw.githubusercontent.com/Yu9191/shortcutstudio-rewrite/refs/heads/baby/dist/request.js
^https:\/\/api\.shortcutstudio\.app\/users\/me\/limits(?:[/?#]|$) url script-response-body https://raw.githubusercontent.com/Yu9191/shortcutstudio-rewrite/refs/heads/baby/dist/response.js
