import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";

export default [
	{
		input: "src/request.dev.js",
		output: {
			file: "dist/request.dev.js",
			format: "es",
			banner: "/* ShortcutStudio Request Script (Dev) - Generated by Rollup */",
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs()],
	},
	{
		input: "src/response.dev.js",
		output: {
			file: "dist/response.dev.js",
			format: "es",
			banner: "/* ShortcutStudio Response Script (Dev) - Generated by Rollup */",
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs()],
	},
];
