import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";

export default [
	{
		input: "src/request.js",
		output: {
			file: "dist/request.js",
			format: "es",
			banner: "/* ShortcutStudio Request Script - Generated by Rollup */",
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs(), terser()],
	},
	{
		input: "src/response.js",
		output: {
			file: "dist/response.js",
			format: "es",
			banner: "/* ShortcutStudio Response Script - Generated by Rollup */",
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs(), terser()],
	},
];
